# This file is generated by soc_gen and will be overwritten next time
# the tool is run. See soc_top/README for information on running soc_gen.
$(VHDLS) += devices.vhd
$(VHDLS) += soc.vhd
$(VHDLS) += pad_ring.vhd
