-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************



library ieee;
use ieee.std_logic_1164.all;

use work.dma_pack.all;
use work.cpu2j0_pack.all;
use work.bist_pack.all;
use work.attr_pack.all;
use work.config.all;








entity dma_db_slave_process is
  generic (  DMA_NUMCH : integer := 64 ;
            DMA_ASYNC : boolean := false ;
            DMA_GRPT  : boolean := true );
  port (  
    clk : in std_logic;
      clk_0_5x : in std_logic;
    clk200 : in std_logic;
    rst : in std_logic;

    db_i : in cpu_data_o_t;
    db_o : out cpu_data_i_t;

    db_peri_i : in cpu_data_i_t;                 
    db_peri_o : out cpu_data_o_t;                
    dbus_o : out bus_ddr_o_t;                    
    dbus_i : in bus_ddr_i_t;                     
    int : out std_logic;
    actp_o       : out actp_o_t; 
    actp_i       : in  actp_i_t;
    dsmrec_ctrl  : out dsmrec_ctrl_t;
    db_dsmreclocal_o : out dsmlocal_cpudata_o_t; 
    db_dsmreclocal_i : in dsmlocal_cpudata_i_t;  
    bi : in bist_scan_t;
    bo : out bist_scan_t
    );

  group local_sigs : local_ports( 
    dbus_o,
    dbus_i
  );
  group dmac : peripheral_bus( 
    db_peri_o,
    db_peri_i);

  attribute soc_port_irq of int : signal is true;
end entity;

architecture bytebus of dma_db_slave_process is
  signal db_word_o : cpu_data_o_t;
  signal db_word_i : cpu_data_i_t;
begin
    dma : configuration work.dma_db_inferred
        generic map (
            DMA_NUMCH => DMA_NUMCH ,
            DMA_ASYNC => DMA_ASYNC ,
            DMA_GRPT => DMA_GRPT
        )
        port map (
            clk => clk ,
            clk200 => clk200 ,
            rst => rst ,
            db_i => db_word_o ,
            db_o => db_word_i ,
            db_peri_i => db_peri_i ,
            db_peri_o => db_peri_o ,
            dbus_o => dbus_o ,
            dbus_i => dbus_i ,
            int => int ,
            actp_o => actp_o ,
            actp_i => actp_i ,
            dsmrec_ctrl => dsmrec_ctrl ,
            db_dsmreclocal_o => db_dsmreclocal_o ,
            db_dsmreclocal_i => db_dsmreclocal_i ,
            bi => bi ,
            bo => bo
        );

   slave_adapter : entity work.bussizesa(rtl)
        port map (
            rst => rst ,
            clk => clk ,
            clk_half => clk_0_5x,
            db_a_o => db_i ,
            db_a_i => db_o ,
            db_b_o => db_word_o,
            db_b_i => db_word_i
        );
end bytebus;
