-- ******************************************************************
-- ******************************************************************
-- This file is generated by soc_gen and will be overwritten next time
-- the tool is run. See soc_top/README for information on running soc_gen.
-- ******************************************************************
-- ******************************************************************
-- ******************************************************************
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.cpu2j0_pack.all;
use work.data_bus_pack.all;
use work.attr_pack.all;
use work.ddrc_cnt_pack.all;

use work.cache_pack.all;

entity icache_modereg_wsbu_slave_process is
  port ( 
   rst : in std_logic;
   clk : in std_logic;
      clk_0_5x : in std_logic;
   
   db_i : in cpu_data_o_t;
   
   db_o : out cpu_data_i_t;
   
   cpu0_ddr_ibus_o : in cpu_instruction_o_t;
   cpu1_ddr_ibus_o : in cpu_instruction_o_t;
   
   ddr_status : in ddr_status_o_t ; 
   db_cctrans_o : out tracpu_data_o_t; 
   cache01sel_ctrl_temp : out std_logic);
  attribute soc_port_global_name of cache01sel_ctrl_temp : signal is "cache01sel_ctrl_temp";
  attribute soc_port_global_name of cpu0_ddr_ibus_o : signal is "cpu0_ddr_ibus_o";
  attribute soc_port_global_name of cpu1_ddr_ibus_o : signal is "cpu1_ddr_ibus_o";
  attribute soc_port_global_name of ddr_status : signal is "ddr_status";
end entity;

architecture bytebus of icache_modereg_wsbu_slave_process is
  signal db_word_o : cpu_data_o_t;
  signal db_word_i : cpu_data_i_t;
begin
    cache_ctrl_wsbu : entity work.icache_modereg_wsbu(with_sbu)
        port map (
            rst => rst ,
            clk => clk ,
            db_i => db_word_o ,
            db_o => db_word_i ,
            cpu0_ddr_ibus_o => cpu0_ddr_ibus_o ,
            cpu1_ddr_ibus_o => cpu1_ddr_ibus_o ,
            ddr_status => ddr_status ,
            db_cctrans_o => db_cctrans_o ,
            cache01sel_ctrl_temp => cache01sel_ctrl_temp
        );

   slave_adapter : entity work.bussizesa(rtl)
        port map (
            rst => rst ,
            clk => clk ,
            clk_half => clk_0_5x,
            db_a_o => db_i ,
            db_a_i => db_o ,
            db_b_o => db_word_o,
            db_b_i => db_word_i
        );
end bytebus;
